# Software Development Environments

## tl;dr

 * Integrated Development Environments (IDEs): we recommend you use one for software development ✔
 * Jupyter notebooks: great for tutorials and as a playground for getting familiar with code, but not great for software engineering 🚸
 * plain text editors: try to avoid, although sometimes you have to use one ⛔

## Integrated Development Environments (IDEs)

 * All-in-one that comes with many features to help to code
 * We think it is worth the (small) effort to learn to use one
 * The two leading IDEs for Python are VS Code and PyCharm
 * We will be demoing useful features in VS Code throughout the week
 * Demo:
    * VS Code workspace introduction
    * Autocomplete
    * Static error checking (linting)
    * Git integration
    * SSH integration

## Jupyter Notebooks 

 * Combination of code cells and Markdown text cells make it useful for writing tutorials
 * Running/rerunning one cell at a time allows you to play around with the code/understand how it works
 * Useful for plotting, solving a problem (think of it as a document)
 * Output depends on order cells are run/rerun -> not good for repeatability
 * Not designed for programming a software package

## Plain text editors

* The "old-school" editors (e.g., vim, emacs, nano, notepad++)
* We generally recommend you avoid doing large amounts of programing in them as the code is prone to bugs
* Sometimes inevitable in astronomy so it is good to learn a little bit of either vim or emacs
* You can use VS Code over ssh, so you should not need to use these very often!

# Object-Oriented and Functional Programming

## tl;dr

 * Object-oriented programming relies on the state of variables to determine the output
    * Good to keep track of something that is changing (e.g., the number of people in a Zoom meeting)
 * Functional programming relies solely on the inputs, which do not change, to determine the output
    * Good for math equations (e.g., computing the inverse of a matrix)
 * Typically, you will want a mix of both programming paradigms

## Object-Oriented Programming
 
![](imgs/oo-meme.png)

## Classes

 * Classes organize variables and functions into a single object
 * Objects can be used to track state - useful model for many things in the world
 * We recommend identifying entities that should become objects and program around this
   * For example, list functions/functionality you want and see how they can be grouped together.
 * Refer to the diagnostic notebook for the basics on class and superclass syntax

Some more subtle things to consider when using classes

  * Creating an object can be slow. Too many object creations can slow down code
  * Could be prone to bugs since function outputs depends on both inputs and the current state of the object

## Object Oriented Programming
    
 * Code structured around objects
 * Depends on changing/"mutable" state of the object (e.g., `self.height`, `self.velocity`, etc.)
 * Most things in the world change, so it makes sense to frame things in this way
 * Activity: finish the following free fall gravity simulator. Use your simulation to determine how long it takes for a particle to the ground from a height of 10 meters. We will poll everyone on what you get.
 * Bonus activity: In the future, we want particles that experience other forces and move in 3D. Write a `Particle` superclass that the `FreeFallParticle` is a subclass of. What fields go into the `Particle` class?


In [1]:
# Object-Oriented Programming

class Particle(object):
    """
    A simulated particle that moves in 3D.

    Args:
        dt (float): timestep of the simulation in seconds
        x, y, z (float): initial position of the particle in cartesian coordinates [m]
        vz, vy, vz (float): initial velocity of the particle in x/y/z [m/s]
    """
    def __init__(self, dt=0.1, x=0, y=0, z=0, vx=0, vy=0, vz=0):
        
        self.x = x
        self.y = y 
        self.z = z

        self.vx = 0
        self.vy = 0
        self.vz = 0

        self.time = 0 # time elapsed [seconds]
        self.dt = dt # timestep of the simulation [seconds]

    def get_num_steps_run(self):
        """
        Function that returns the number of timesteps that have run by comparing self.time with self.dt

        Returns:
            num_steps (int): number of time steps already completed in the simulation
        """
        num_steps = int(self.time / self.dt)
        return num_steps


class FreeFallParticle(Particle):
    """
    Simulate a particle falling due to Earth's gravity. Particle is stationary at first

    Args:
        height (float): a height in meters
        dt (float): timestep of the simulation in seconds
    """
    def __init__(self, height, dt=0.1):
        """
        Function that is run to initialize the class
        """
        # let's initalize it's parent class
        super().__init__(dt=dt, z=height)

        # note that we are not using the astropy.units class here as we haven't talked about it yet! But it could be useful!
        self.g = -9.8 # gravitational acceleration (Don't change) [meters/second^2]


    """
    [Advanced topic]
    We replaced the self.height and self.velocity fields and turned them into "getter" and "setter" functions because they 
    now are essentailly just mirrors for self.z and self.vz. It is a little clunky this way, so perhaps we should have taken
    a bit longer and thought about the naming of our variables in the FreeFallParticle class to make them more generalizable 
    in the Particle class... If they were just named z and vz instead, we wouldn't needed these lines of code!
    """
    # getter function for height
    @property
    def height(self):
        return self.z
    # setter function for height
    @height.setter
    def height(self, val):
        self.z = val

    # getter function for velocity
    @property
    def velocity(self):
        return self.vz
    # setter function for velocity
    @velocity.setter
    def velocity(self, val):
        self.vz = val

    ##### Activity ######
    """
    Add functionality to advance the particle's height by one time step at a time. (hint: implement the function below).
    Then use this code to calculate how long it takes for the particle to fall down from a height of 10 meters.

    Some useful equations for how to calculate the particle's new state at the next time step.
    Pseudo code below:
    acceleration = g
    new_velocity = current_velocity + acceleration * dt
    new_height = current_height + new_velocity * dt

    Add inputs and outputs. 
    """
    def simulate_timestep(self):
        """
        Advance the simulation time by a single timestep (self.dt). 
        Update the simulation with the new time, height, and velocity

        Returns:
            height (float): the current height in meters
        """
        self.velocity += self.g * self.dt
        self.height += self.velocity * self.dt
        self.time += self.dt

        return self.height

In [2]:
# Here's how you could call this function
ball = FreeFallParticle(10) # start out a 10 m above the ground
print(ball.time, ball.height)

while ball.height > 0:
    ball.simulate_timestep()
    print(ball.time, ball.height) # time should move forward by 0.1 seconds

0 10
0.1 9.902
0.2 9.706
0.30000000000000004 9.411999999999999
0.4 9.02
0.5 8.53
0.6 7.941999999999999
0.7 7.255999999999999
0.7999999999999999 6.4719999999999995
0.8999999999999999 5.589999999999999
0.9999999999999999 4.6099999999999985
1.0999999999999999 3.5319999999999983
1.2 2.355999999999998
1.3 1.0819999999999976
1.4000000000000001 -0.2900000000000029


## Functional Programming

![](imgs/fp-meme.png)

## Functional Programming

 * Key paradigm: functions outputs depend solely on the inputs
    * Easier to guarantee correctness
    * More messy to track changing state of things
 * Functional programming != no objects. Objects however are static data structures.
    * You need to create a new object if you want to change an object
 * Useful for math problems, physics equations, unit conversions
    * `import astropy.units as u; u.m.to(u.nm)`

In [3]:
# Functional Programming Example. 

class FuncParticle(object):
    """
    A particle with a given height and vertical instantaneous velocity

    Args:
        height (float): height of the object currently in meters
        velocity (float): velocity of the object in meters. Default is 0 (at rest)
    """
    def __init__(self, height, velocity=0):
        self.height = height
        self.velocity = velocity

def freefall_timestep(thing, dt=0.1):
    """
    Simulate free fall of the particle for a small time step

    Args:
        thing (FuncParticle): the current position and velocity of the particle
        dt (float): optional float that specifies the timestep in seconds

    Returns:
        new_thing (FuncParticle): the updated position and velocity of the particle
    """
    dt_units = dt
    new_velocity = thing.velocity + -9.8 * dt_units
    new_height = thing.height + new_velocity * dt_units

    new_thing = FuncParticle(new_height, new_velocity)
    return new_thing


ball = FuncParticle(1) # start a ball at 1 m
ball_states = [ball]
print(0, ball.height)
dt = 0.1
time = 0

for i in range(5):
    new_ball = freefall_timestep(ball_states[-1], dt)
    ball_states = ball_states + [new_ball,]
    time += dt
    print(time, new_ball.height)


# Running the function with the same inputs will return the same result
# This generally would not happen with object oriented programming
# When is this good or bad?
output_ball_1 = freefall_timestep(ball, dt)
output_ball_2 = freefall_timestep(ball, dt)
print("Are these the same?", output_ball_1.height, output_ball_2.height)



0 1
0.1 0.902
0.2 0.706
0.30000000000000004 0.4119999999999999
0.4 0.01999999999999985
0.5 -0.4700000000000002
Are these the same? 0.902 0.902


## Object Oriented vs Functional Programming

 * Object oriented programming is good when things change (e.g., the position of a planet, the current image being analyzed)
 * Functional programming is good to deterministic things (e.g., math equations, making sure you do not accidentally apply the same function twice)
 * Most packages use both

## Bonus Activity

Implement the function to get all of the previous heights and their corresponding times the free falling object was at. For example, if the object was at `height = 1` at `time = 0`, `height = 0.902` at `t = 0.1`, and `height = 0.706` at `t = 0.2`, the function should return `[1, 0.902, 0.706]` for the heights and `[0, 0.1, 0.2]` for the corresponding times. Choose to implement it either in the object oriented or functional framework we provided. If you have time, try the other one too! 


In [4]:
###################
# OOP method: 
###################

class FreeFallParticle(Particle):
    """
    Simulate a particle falling due to Earth's gravity. Particle is stationary at first

    Args:
        height (float): a height in meters
        dt (float): timestep of the simulation in seconds
    """
    def __init__(self, height, dt=0.1):
        """
        Function that is run to initialize the class
        """
        # let's initalize it's parent class
        super().__init__(dt=dt, z=height)

        # note that we are not using the astropy.units class here as we haven't talked about it yet! But it could be useful!
        self.g = -9.8 # gravitational acceleration (Don't change) [meters/second^2]

        # record the previous heights!!
        self.prev_heights = [height]
        self.prev_times = [0]

    # getter function for height
    @property
    def height(self):
        return self.z
    # setter function for height
    @height.setter
    def height(self, val):
        self.z = val

    # getter function for velocity
    @property
    def velocity(self):
        return self.vz
    # setter function for velocity
    @velocity.setter
    def velocity(self, val):
        self.vz = val

    ##### Activity ######
    def simulate_timestep(self):
        """
        Advance the simulation time by a single timestep (self.dt). 
        Update the simulation with the new time, height, and velocity

        Returns:
            height (float): the current height in meters
        """
        self.velocity += self.g * self.dt
        self.height += self.velocity * self.dt
        self.time += self.dt

        # add previous times and heights to the history
        self.prev_times.append(self.time)
        self.prev_heights.append(self.height)

        return self.height

    def get_height_history(self):
        """
        Returns all previous times and heights the object has been at

        Returns:
            times (np.array): previous times 
            heights (np.array): previous heights
        """
        return self.prev_times, self.prev_heights

ball = FreeFallParticle(1) 
ball.simulate_timestep()
ball.simulate_timestep()
my_times, my_heights = ball.get_height_history()
print('Times [s] (OOP): {}'.format(my_times))
print('Heights [m] (OOP): {}\n'.format(my_heights))

######################
# functional method:
######################

def falling_history_func(initial_height, endtime, dt=0.1):
    """
    Return the heights and times an object falls through over the simulation. Uses 
    functional approach.

    Args: 
        initial_height (float): height [m] at time = 0
        endtime (float): timestamp to stop at [s]
        dt (float): timestep [s]
    
    Returns:
        tuple of 
            list of float: times [s]
            list of float: heights [m]
    """

    myParticle = FuncParticle(initial_height)
    particle_list = [myParticle]
    time = 0
    times = []
    heights = []

    while time <= endtime:

        times.append(time)
        heights.append(particle_list[-1].height)

        newParticle = freefall_timestep(particle_list[-1], dt)
        particle_list.append(newParticle)

        time += dt

    return times, heights


my_times, my_heights = falling_history_func(1, 0.2)
print('Times [s] (functional): {}'.format(my_times))
print('Heights [m] (functional): {}\n'.format(my_heights))

Times [s] (OOP): [0, 0.1, 0.2]
Heights [m] (OOP): [1, 0.902, 0.706]

Times [s] (functional): [0, 0.1, 0.2]
Heights [m] (functional): [1, 0.902, 0.706]

